CREATE TABLE IF NOT EXISTS inventory_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_patrimonio VARCHAR(64) NOT NULL,
  codigo_patrimonio VARCHAR(64) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  categoria VARCHAR(120),
  marca VARCHAR(120),
  modelo VARCHAR(120),
  numero_serie VARCHAR(120),
  data_aquisicao DATE,
  fornecedor VARCHAR(160),
  nota_fiscal VARCHAR(80),
  valor_aquisicao DECIMAL(12,2),
  forma_aquisicao VARCHAR(80),
  unidade VARCHAR(120),
  setor VARCHAR(120),
  localizacao_endereco VARCHAR(200),
  localizacao_cep VARCHAR(12),
  localizacao_complemento VARCHAR(160),
  responsavel VARCHAR(160),
  status VARCHAR(60),
  condicao VARCHAR(60),
  data_ultimo_inventario DATE,
  vida_util_anos INT,
  taxa_depreciacao DECIMAL(6,2),
  valor_contabil DECIMAL(12,2),
  centro_custo VARCHAR(120),
  garantia_ate DATE,
  historico_manutencao TEXT,
  custo_manutencao DECIMAL(12,2),
  data_baixa DATE,
  motivo_baixa VARCHAR(160),
  valor_baixa DECIMAL(12,2),
  qr_token VARCHAR(64) UNIQUE,
  link_qr TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
